import type { ComponentType } from "react";
import { FaTheaterMasks } from "react-icons/fa";
import {
	SiApollographql,
	SiBun,
	SiCss3,
	SiCypress,
	SiDeno,
	SiDocker,
	SiGit,
	SiGithubactions,
	SiGo,
	SiGraphql,
	SiHtml5,
	SiJavascript,
	SiJest,
	SiJira,
	SiMaterialdesign,
	SiMongodb,
	SiNestjs,
	SiNextdotjs,
	SiNginx,
	SiNodedotjs,
	SiNx,
	SiPostgresql,
	SiPrisma,
	SiPython,
	SiReact,
	SiReactquery,
	SiReactrouter,
	SiRedis,
	SiRedux,
	SiRemix,
	SiRust,
	SiScala,
	SiSupabase,
	SiTailwindcss,
	SiTerraform,
	SiTurborepo,
	SiTypescript,
	SiVercel,
	SiVite,
	SiVitest,
	SiWebpack,
	SiZod,
} from "react-icons/si";
import { VscAzure } from "react-icons/vsc";

export const iconMap: Record<string, ComponentType<{ className?: string }>> = {
	SiApollographql: SiApollographql,
	SiBun: SiBun,
	SiCss3: SiCss3,
	SiCypress: SiCypress,
	SiDeno: SiDeno,
	SiDocker: SiDocker,
	SiGit: SiGit,
	SiGithubactions: SiGithubactions,
	SiGo: SiGo,
	SiGraphql: SiGraphql,
	SiHtml5: SiHtml5,
	SiJavascript: SiJavascript,
	SiJest: SiJest,
	SiJira: SiJira,
	SiMaterialdesign: SiMaterialdesign,
	SiMongodb: SiMongodb,
	SiNestjs: SiNestjs,
	SiNextdotjs: SiNextdotjs,
	SiNginx: SiNginx,
	SiNodedotjs: SiNodedotjs,
	SiNx: SiNx,
	SiPostgresql: SiPostgresql,
	SiPrisma: SiPrisma,
	SiPython: SiPython,
	SiReact: SiReact,
	SiReactquery: SiReactquery,
	SiReactrouter: SiReactrouter,
	SiRedis: SiRedis,
	SiRedux: SiRedux,
	SiRemix: SiRemix,
	SiRust: SiRust,
	SiScala: SiScala,
	SiSupabase: SiSupabase,
	SiTailwindcss: SiTailwindcss,
	SiTerraform: SiTerraform,
	SiTurborepo: SiTurborepo,
	SiTypescript: SiTypescript,
	SiVercel: SiVercel,
	SiVite: SiVite,
	SiVitest: SiVitest,
	SiWebpack: SiWebpack,
	SiZod: SiZod,
	FaTheaterMasks: FaTheaterMasks,
	VscAzure: VscAzure,
};
