export const PROJECTS = [
  {
    title: "Farah Freight Group",
    category: "Frontend",
    description: "Company website for Farah Freight Group. Single Page Application created using NextJS and Nodemailer for sending emails.",
    liveLink: "https://farahfg.com/",
    githubLink: "https://github.com/propbono/farahfg.com",
    stack: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Nodemailer", "Vercel"],
    image: "/work/p1.jpg",
  },
  {
    title: "Gemprint",
    category: "Fullstack",
    description:
      "Company website for Gemprint. Single Page Application created using NextJS and NextAuth. Currently working on adding Dashboard to manage print orders.",
    liveLink: "https://gemprint.ca/",
    githubLink: "https://github.com/propbono/gemprint.ca",
    stack: ["Next.js", "TypeScript", "Tailwind CSS", "Prisma", "Vercel", "Resend"],
    image: "/work/p2.jpg",
  },
  {
    title: "Wizzcode Music App",
    category: "Frontend",
    description:
      "Sample music app to test React Query hooks and write some cool tests in Vitest. It communicates with Itunes API and pull some albums using React Query.",
    liveLink: "https://wizcode-music.vercel.app/",
    githubLink: "https://github.com/propbono/gmozer.ca",
    stack: ["Remix.js", "TypeScript", "Tailwind CSS", "Vite", "Vercel"],
    image: "/work/p3.jpg",
  },
  {
    title: "Propbono Portfolio - new",
    category: "Fullstack",
    description: "Propbono portfolio website presenting some of the projects that I worked on.",
    liveLink: "https://gmozer.ca/",
    githubLink: "https://github.com/propbono/next-gmozer.ca",
    stack: ["Next.js", "TypeScript", "Tailwind CSS", "FramerMotion", "Vercel"],
    image: "/work/p4.jpg",
  },
  {
    title: "Propbono Portfolio - old",
    category: "Frontend",
    description: "Propbono portfolio website presenting some of the projects that I worked on. Written in RemixJS.",
    liveLink: "https://gmozer-old.vercel.app/",
    githubLink: "https://github.com/propbono/gmozer.ca",
    stack: ["Remix.js", "TypeScript", "Tailwind CSS", "Vite", "Vercel"],
    image: "/work/p5.jpg",
  },
  {
    title: "SWM Interview 2024",
    category: "Algorithm",
    description:
      "Interview task is composed from two parts, coding exercise and an essay. Below you can see the information about programming task. Write a function that receives two sequences: A and B of integers and returns one sequence C. Sequence C should contain all elements from sequence A (maintaining the order) except those, that are present in sequence B p times, where p is a prime number.",
    liveLink: "#",
    githubLink: "https://github.com/propbono/swm-interview-2024",
    stack: ["TypeScript"],
    image: "/work/p6.jpg",
  },
  {
    title: "Farah Financial Group - development",
    category: "Algorithm",
    description: "Company website for Farah Financial Group. Web application utilizing NextJS App router and Resend for sending emails.",
    liveLink: "#",
    githubLink: "https://github.com/propbono/farahfinancialgroup.ca",
    stack: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Resend", "Vercel"],
    image: "/work/p7.jpg",
  },
];
