import {
	SiCss3,
	SiCypress,
	SiDocker,
	SiGit,
	SiGithubactions,
	SiHtml5,
	SiJavascript,
	SiJest,
	SiJira,
	SiMaterialdesign,
	SiMongodb,
	SiNextdotjs,
	SiNodedotjs,
	SiNx,
	SiPostgresql,
	SiPrisma,
	SiPython,
	SiReact,
	SiReactquery,
	SiReactrouter,
	SiRedux,
	SiRemix,
	SiTailwindcss,
	SiTypescript,
	SiVercel,
	SiVite,
	SiVitest,
	SiWebpack,
} from "react-icons/si";

export const SKILLS = {
	items: [
		{ link: "https://react.dev/", name: "React", icon: <SiReact /> },
		{ link: "https://nextjs.org/", name: "NextJS", icon: <SiNextdotjs /> },
		{ link: "https://remix.run/", name: "RemixJS", icon: <SiRemix /> },
		{
			link: "https://www.typescriptlang.org/",
			name: "TypeScript",
			icon: <SiTypescript />,
		},
		{
			link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
			name: "JavaScript",
			icon: <SiJavascript />,
		},
		{ link: "https://nodejs.org/", name: "Node.js", icon: <SiNodedotjs /> },
		{
			link: "https://html.spec.whatwg.org/",
			name: "HTML 5",
			icon: <SiHtml5 />,
		},
		{ link: "https://www.w3.org/Style/CSS/", name: "CSS 3", icon: <SiCss3 /> },
		{
			link: "https://tailwindcss.com/",
			name: "Tailwind CSS",
			icon: <SiTailwindcss />,
		},
		{
			link: "https://mui.com/",
			name: "Material UI",
			icon: <SiMaterialdesign />,
		},
		{ link: "https://git-scm.com/", name: "Git", icon: <SiGit /> },
		{
			link: "https://github.com/features/actions",
			name: "GitHub Actions",
			icon: <SiGithubactions />,
		},
		{ link: "https://jestjs.io/", name: "Jest", icon: <SiJest /> },
		{ link: "https://vitest.dev/", name: "Vitest", icon: <SiVitest /> },
		{ link: "https://www.cypress.io/", name: "Cypress", icon: <SiCypress /> },
		{ link: "https://vitejs.dev/", name: "Vite", icon: <SiVite /> },
		{ link: "https://vercel.com/", name: "Vercel", icon: <SiVercel /> },
		{ link: "https://webpack.js.org/", name: "Webpack", icon: <SiWebpack /> },
		{ link: "https://nx.dev/", name: "NX Monorepo", icon: <SiNx /> },
		{ link: "https://www.mongodb.com/", name: "MongoDB", icon: <SiMongodb /> },
		{
			link: "https://www.postgresql.org/",
			name: "PostgreSQL",
			icon: <SiPostgresql />,
		},
		{ link: "https://www.prisma.io/", name: "Prisma", icon: <SiPrisma /> },
		{ link: "https://redux.js.org/", name: "Redux", icon: <SiRedux /> },
		{
			link: "https://tanstack.com/query/latest",
			name: "React Query",
			icon: <SiReactquery />,
		},
		{
			link: "https://reactrouter.com/",
			name: "React Router",
			icon: <SiReactrouter />,
		},
		{
			link: "https://www.atlassian.com/software/jira",
			name: "Jira",
			icon: <SiJira />,
		},
		{ link: "https://www.python.org/", name: "Python", icon: <SiPython /> },
		{ link: "https://www.docker.com/", name: "Docker", icon: <SiDocker /> },
	],
};
